const run3dState = {
    params: null,
    mapParam: '',
    mapSource: '',
    mapParamName: '',
    ready: false,
    gridSize: 0,
    grid: null,
    bfsPath: null,
    solvable: false,
    wallCount: 0,
    sliceOffset: 0,
    crossSection: null,
    player: { x: 0, y: 0 },
    yaw: 0,
    pitch: 0,
    pointerLocked: false,
    keys: Object.create(null),
    lastFrameAt: 0,
    viewMode: 'continuous_slice_irl',
    completed: false,
};
