const run4dState = {
    params: null,
    mapParam: '',
    mapSource: '',
    ready: false,
    gridSize: 0,
    grid: null,
    bfsPath: null,
    solvable: false,
    wallCount: 0,
    hyperLayer: 0,
    hyperSliceOffset: 0,
    crossSection: null,
    player: { x: 0, y: 0, z: 0 },
    yaw: 0,
    pitch: 0,
    pointerLocked: false,
    xrayHeld: false,
    shiftPulse: 0,
    shiftDirection: 0,
    keys: Object.create(null),
    lastFrameAt: 0,
    completed: false,
};
